- id: '1636770622333'
  alias: FireTV Backlights
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.fire_tv
    to: 'off'
    id: tv_off
  - platform: state
    entity_id: media_player.fire_tv
    id: tv_on
    from: 'off'
  condition: []
  action:
  - type: turn_off
    device_id: 69b1ccedd2cc904b45e26ace20117573
    entity_id: light.tv_backlights
    domain: light
  - choose:
    - conditions:
      - condition: trigger
        id: tv_off
      sequence:
      - type: turn_off
        device_id: 69b1ccedd2cc904b45e26ace20117573
        entity_id: light.tv_backlights
        domain: light
    - conditions:
      - condition: trigger
        id: tv_on
      sequence:
      - type: turn_on
        device_id: 69b1ccedd2cc904b45e26ace20117573
        entity_id: light.tv_backlights
        domain: light
    default: []
  mode: single
- id: '1636905441779'
  alias: Bedroom Light Management
  description: Control bedroom lights based on time of day and buttons pressed.
  trigger:
  - device_id: 5d4519c5061ba4bf32d470d259c61a6e
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
    id: light_switch_off
  - platform: time
    at: 00:00:00
    id: midnight
  - device_id: 5d4519c5061ba4bf32d470d259c61a6e
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
    id: light_switch_on
  - platform: time
    at: '23:00:00'
    id: 11pm
  - device_id: 5d4519c5061ba4bf32d470d259c61a6e
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_up
    id: light_switch_on_long_press
  - device_id: 43ef8bdd769458f414690d21141976db
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
    id: remote_toggle
  - device_id: 43ef8bdd769458f414690d21141976db
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: dim_up
    id: remote_up
  - device_id: 43ef8bdd769458f414690d21141976db
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: dim_down
    id: remote_down
  condition: []
  action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: trigger
          id: light_switch_off
        - condition: trigger
          id: midnight
        - condition: and
          conditions:
          - condition: trigger
            id: remote_toggle
          - condition: device
            type: is_on
            device_id: ec3f798bc249a8599b62f0fab50dc6a5
            entity_id: switch.fairy_lights
            domain: switch
      sequence:
      - scene: scene.bedroom_lights_off
    - conditions:
      - condition: or
        conditions:
        - condition: and
          conditions:
          - condition: or
            conditions:
            - condition: trigger
              id: light_switch_on
            - condition: and
              conditions:
              - condition: trigger
                id: remote_toggle
              - condition: device
                type: is_off
                device_id: ec3f798bc249a8599b62f0fab50dc6a5
                entity_id: switch.fairy_lights
                domain: switch
            - condition: trigger
              id: remote_down
          - condition: or
            conditions:
            - condition: sun
              before: sunrise
            - condition: sun
              after: sunset
        - condition: trigger
          id: 11pm
      sequence:
      - scene: scene.bedroom_lights_low
    - conditions:
      - condition: or
        conditions:
        - condition: and
          conditions:
          - condition: or
            conditions:
            - condition: trigger
              id: light_switch_on
            - condition: and
              conditions:
              - condition: trigger
                id: remote_toggle
              - condition: device
                type: is_off
                device_id: ec3f798bc249a8599b62f0fab50dc6a5
                entity_id: switch.fairy_lights
                domain: switch
          - condition: or
            conditions:
            - condition: sun
              before: sunset
            - condition: sun
              after: sunrise
        - condition: trigger
          id: light_switch_on_long_press
        - condition: trigger
          id: remote_up
      sequence:
      - scene: scene.bedroom_lights_high
    default: []
  mode: queued
  max: 10
- id: '1636942701463'
  alias: Kitchen Lights Sync
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 95f048b21aa9bd471dffdaa39672611d
    entity_id: switch.kitchen_light
    domain: switch
    id: lights_on
  - platform: device
    type: turned_off
    device_id: 95f048b21aa9bd471dffdaa39672611d
    entity_id: switch.kitchen_light
    domain: switch
    id: lights_off
  condition: []
  action:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: trigger
          id: lights_on
        - condition: state
          entity_id: sun.sun
          state: above_horizon
      sequence:
      - service: light.turn_on
        data:
          color_temp: 270
          brightness_pct: 100
        target:
          entity_id: light.kitchen_fan_lights
    - conditions:
      - condition: trigger
        id: lights_off
      sequence:
      - service: light.turn_off
        target:
          entity_id: light.kitchen_fan_lights
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: sun.sun
          state: below_horizon
        - condition: trigger
          id: lights_on
      sequence:
      - service: light.turn_on
        data:
          color_temp: 370
          brightness_pct: 100
        target:
          entity_id: light.kitchen_fan_lights
    default: []
  mode: single
- id: '1636943258539'
  alias: 'Hallway Button Pressed: Toggle Hallway Light'
  description: ''
  trigger:
  - device_id: f472bbaf5fdfa4eed5289700190fa35a
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - type: toggle
    device_id: 0054a4ac2d37c4fa93d18e2e92909d66
    entity_id: switch.hallway_light
    domain: switch
  mode: single
- id: '1636996449089'
  alias: Study Lights
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: 98ad68c37e01ed37cfff94de4e243af8
    entity_id: binary_sensor.gd_macbook_active
    domain: binary_sensor
    id: macbook_active
  - type: turned_off
    platform: device
    device_id: 98ad68c37e01ed37cfff94de4e243af8
    entity_id: binary_sensor.gd_macbook_active
    domain: binary_sensor
    id: macbook_inactive
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: macbook_active
      sequence:
      - service: light.turn_on
        target:
          area_id: study
    - conditions:
      - condition: trigger
        id: macbook_inactive
      sequence:
      - service: light.turn_off
        target:
          area_id: study
    default: []
  mode: restart
- id: '1637124125495'
  alias: 'Arrive Home: Hallway Light On'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.home_mode
    from: away
  condition: []
  action:
  - wait_for_trigger:
    - type: opened
      platform: device
      device_id: 39f88ffb037953a6837e5054f1ee0be8
      entity_id: binary_sensor.front_door
      domain: binary_sensor
    continue_on_timeout: false
  - type: turn_on
    device_id: 0054a4ac2d37c4fa93d18e2e92909d66
    entity_id: switch.hallway_light
    domain: switch
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 0054a4ac2d37c4fa93d18e2e92909d66
    entity_id: switch.hallway_light
    domain: switch
  mode: single
- id: '1637429968086'
  alias: Kitchen Motion Lights
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 9882d00ad4439fbf80486d60b583e169
    entity_id: binary_sensor.kitchen_motion_sensor
    domain: binary_sensor
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: sensor.home_mode
      state: home
    - condition: state
      entity_id: sensor.home_mode
      state: tv
  - condition: or
    conditions:
    - condition: not
      conditions:
      - condition: state
        entity_id: weather.home
        state: sunny
    - condition: state
      entity_id: sun.sun
      state: below_horizon
  action:
  - service: switch.turn_on
    target:
      area_id: kitchen
  - wait_for_trigger:
    - type: no_motion
      platform: device
      device_id: 9882d00ad4439fbf80486d60b583e169
      entity_id: binary_sensor.kitchen_motion_sensor
      domain: binary_sensor
    continue_on_timeout: true
    timeout: 00:25:00
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      area_id: kitchen
  mode: restart
- id: '1637817372671'
  alias: Lights off at midnight
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id:
      - study
      - study
      - kitchen
      - living_room
  - service: switch.turn_off
    target:
      entity_id:
      - switch.cube_light
      - switch.fairy_lights
      - switch.hallway_light
      - switch.kitchen_light
  mode: single
- id: '1637979359844'
  alias: Automatic Blinds
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    id: sunrise
    offset: '-45'
  - platform: sun
    event: sunset
    id: sunset
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: sunrise
      sequence:
      - service: cover.open_cover
        target:
          area_id: bedroom
    - conditions:
      - condition: trigger
        id: sunset
      sequence:
      - service: cover.close_cover
        target:
          area_id: bedroom
    default: []
  mode: single
- id: '1638224503187'
  alias: Closet Light
  description: ''
  trigger:
  - platform: state
    entity_id: group.closet_doors
    id: door_open
    to: 'on'
  - platform: state
    entity_id: group.closet_doors
    from: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: door_open
      sequence:
      - service: light.turn_on
        target:
          area_id: bedroom_closet
    default:
    - service: light.turn_off
      target:
        area_id: bedroom_closet
  mode: queued
  max: 10
- id: '1638226343221'
  alias: Toggle Bedroom Blinds
  description: ''
  trigger:
  - device_id: f472bbaf5fdfa4eed5289700190fa35a
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: remote_button_long_press
  - device_id: 5d4519c5061ba4bf32d470d259c61a6e
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_down
  condition: []
  action:
  - choose:
    - conditions:
      - condition: device
        device_id: d9d9e42e45e105ad8b430a2618b8e8df
        domain: cover
        entity_id: cover.bedroom_side_blinds
        type: is_open
      sequence:
      - service: cover.close_cover
        target:
          area_id: bedroom
    - conditions:
      - condition: device
        device_id: d9d9e42e45e105ad8b430a2618b8e8df
        domain: cover
        entity_id: cover.bedroom_side_blinds
        type: is_closed
      sequence:
      - service: cover.open_cover
        target:
          area_id: bedroom
    default: []
  mode: single
- id: '1639000471493'
  alias: Wallmote Quad Buttons
  description: ''
  use_blueprint:
    path: marisa/wallmote-quad.yaml
    input:
      button_1_pressed:
      - service: light.toggle
        target:
          device_id:
          - 3c2d9a21e111aa94461e00be3ee8049a
          - 81325d520d5e6a537adab3c03b012562
      wallmote_quad_device: 2215822cc9e1c7592c0516ae781156f9
      button_4_pressed:
      - service: switch.turn_off
        target:
          device_id:
          - 95f048b21aa9bd471dffdaa39672611d
          - 0054a4ac2d37c4fa93d18e2e92909d66
      button_2_pressed:
      - service: homeassistant.toggle
        target:
          device_id: 663c92fa8127140d4ac20bd6b876d974
- id: '1642101052868'
  alias: Morning Lights
  description: ''
  trigger:
  - platform: state
    entity_id: sun.sun
    to: above_horizon
  condition: []
  action:
  - service: light.turn_on
    target:
      device_id: 791cf67ec07bd1f310257dd2da0ebf09
  - service: switch.turn_on
    target:
      device_id: 663c92fa8127140d4ac20bd6b876d974
  mode: single
- id: '1642361541314'
  alias: Bedroom Motion Lights
  description: ''
  trigger:
  - platform: state
    entity_id: switch.alexa_orb_motion_sensor
    to: 'on'
  - platform: state
    entity_id: switch.bedroom_wyze_person_sensor
    to: 'on'
  - type: motion
    platform: device
    device_id: 506192e8bb855dd18804e111cc31fcb0
    entity_id: binary_sensor.bedroom_motion
    domain: binary_sensor
    id: motion
  condition:
  - condition: state
    entity_id: sensor.home_mode
    state: home
  - condition: and
    conditions:
    - condition: device
      device_id: 07cebfd898c6d67cc75dddf37f6ff640
      domain: cover
      entity_id: cover.bedroom_back_blinds
      type: is_closed
    - condition: device
      device_id: 7cd813fe0c0d50a9c2cc3c98fe8f907c
      domain: cover
      entity_id: cover.bedroom_side_blinds
      type: is_closed
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.bedroom_lights_high
    data:
      transition: 1
  - choose:
    - conditions:
      - condition: trigger
        id: motion
      sequence:
      - wait_for_trigger:
        - type: no_motion
          platform: device
          device_id: 506192e8bb855dd18804e111cc31fcb0
          entity_id: binary_sensor.bedroom_motion
          domain: binary_sensor
        continue_on_timeout: false
    default:
    - delay:
        hours: 0
        minutes: 5
        seconds: 0
        milliseconds: 0
  - service: scene.turn_on
    target:
      entity_id: scene.bedroom_lights_off
    data:
      transition: 5
  mode: restart
- id: '1643403428879'
  alias: Run Vacuum when Away
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.home_mode
    to: away
    id: away
  - platform: time
    at: 04:00:00
    id: reset
  - platform: state
    entity_id: sensor.home_mode
    id: return_home
    from: away
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: away
      - condition: state
        entity_id: input_boolean.vacuum_has_run
        state: 'off'
      sequence:
      - device_id: 90a48f20da662fdf57ea0a0502538732
        domain: vacuum
        entity_id: vacuum.sharkboy
        type: clean
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_has_run
    - conditions:
      - condition: trigger
        id: reset
      sequence:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_has_run
    - conditions:
      - condition: trigger
        id: return_home
      sequence:
      - device_id: 90a48f20da662fdf57ea0a0502538732
        domain: vacuum
        entity_id: vacuum.sharkboy
        type: dock
    default: []
  mode: restart
- id: '1643506741806'
  alias: Set Air Purifier Speeds
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.home_mode
    to: night
    id: sleep
  - platform: state
    entity_id: sensor.home_mode
    from: night
    id: awake
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: sleep
      sequence:
      - service: fan.set_preset_mode
        target:
          entity_id: fan.air_purifier
        data:
          preset_mode: sleep
    - conditions:
      - condition: trigger
        id: awake
      sequence:
      - service: fan.set_speed
        target:
          entity_id: fan.air_purifier
        data:
          speed: low
    default: []
  mode: single
