- id: '1636770622333'
  alias: FireTV Backlights
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.fire_tv
    to: 'off'
    id: tv_off
  - platform: state
    entity_id: media_player.fire_tv
    id: tv_on
    from: 'off'
  condition: []
  action:
  - type: turn_off
    device_id: 69b1ccedd2cc904b45e26ace20117573
    entity_id: light.tv_backlights
    domain: light
  - choose:
    - conditions:
      - condition: trigger
        id: tv_off
      sequence:
      - type: turn_off
        device_id: 69b1ccedd2cc904b45e26ace20117573
        entity_id: light.tv_backlights
        domain: light
    - conditions:
      - condition: trigger
        id: tv_on
      sequence:
      - type: turn_on
        device_id: 69b1ccedd2cc904b45e26ace20117573
        entity_id: light.tv_backlights
        domain: light
    default: []
  mode: single
- id: '1636905441779'
  alias: Bedroom Light Management
  description: Control bedroom lights based on time of day and buttons pressed.
  trigger:
  - device_id: 36ba91f41f19c8a6fa4d4f915da8020c
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
    id: light_switch_off
  - platform: time
    at: 00:00:00
    id: midnight
  - device_id: 36ba91f41f19c8a6fa4d4f915da8020c
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
    id: light_switch_on
  - platform: time
    at: '23:00:00'
    id: 11pm
  - device_id: 36ba91f41f19c8a6fa4d4f915da8020c
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_up
    id: light_switch_on_long_press
  - device_id: f0574405ffb61d939f67270bd80027eb
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
    id: remote_toggle
  - device_id: f0574405ffb61d939f67270bd80027eb
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: dim_up
    id: remote_up
  - device_id: f0574405ffb61d939f67270bd80027eb
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: dim_down
    id: remote_down
  condition: []
  action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: trigger
          id: light_switch_off
        - condition: trigger
          id: midnight
        - condition: and
          conditions:
          - condition: trigger
            id: remote_toggle
          - condition: device
            type: is_on
            device_id: e7ab46b05b6bc6bf88eb601cd0a491a3
            entity_id: switch.fairy_lights
            domain: switch
      sequence:
      - scene: scene.bedroom_lights_off
    - conditions:
      - condition: or
        conditions:
        - condition: and
          conditions:
          - condition: or
            conditions:
            - condition: trigger
              id: light_switch_on
            - condition: and
              conditions:
              - condition: trigger
                id: remote_toggle
              - condition: device
                type: is_off
                device_id: e7ab46b05b6bc6bf88eb601cd0a491a3
                entity_id: switch.fairy_lights
                domain: switch
            - condition: trigger
              id: remote_down
          - condition: or
            conditions:
            - condition: sun
              before: sunrise
            - condition: sun
              after: sunset
        - condition: trigger
          id: 11pm
      sequence:
      - scene: scene.bedroom_lights_low
    - conditions:
      - condition: or
        conditions:
        - condition: and
          conditions:
          - condition: or
            conditions:
            - condition: trigger
              id: light_switch_on
            - condition: and
              conditions:
              - condition: trigger
                id: remote_toggle
              - condition: device
                type: is_off
                device_id: e7ab46b05b6bc6bf88eb601cd0a491a3
                entity_id: switch.fairy_lights
                domain: switch
          - condition: or
            conditions:
            - condition: sun
              before: sunset
            - condition: sun
              after: sunrise
        - condition: trigger
          id: light_switch_on_long_press
        - condition: trigger
          id: remote_up
      sequence:
      - scene: scene.bedroom_lights_high
    default: []
  mode: queued
  max: 10
- id: '1636942701463'
  alias: Kitchen Lights Sync
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: c136c02ac81d79ade4781284c42869bc
    entity_id: switch.kitchen_light
    domain: switch
    id: lights_on
  - platform: device
    type: turned_off
    device_id: c136c02ac81d79ade4781284c42869bc
    entity_id: switch.kitchen_light
    domain: switch
    id: lights_off
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: lights_on
      sequence:
      - type: turn_on
        device_id: 344e7812953a6847df3d8527d9e86bd8
        entity_id: light.fan_light_1
        domain: light
      - type: turn_on
        device_id: 35807f1c961ef52564fc8671315f9c00
        entity_id: light.fan_light_2
        domain: light
      - type: turn_on
        device_id: f58957d7536a588f98369305882c9e6a
        entity_id: light.fan_light_3
        domain: light
    - conditions:
      - condition: trigger
        id: lights_off
      sequence:
      - type: turn_off
        device_id: 344e7812953a6847df3d8527d9e86bd8
        entity_id: light.fan_light_1
        domain: light
      - type: turn_off
        device_id: 35807f1c961ef52564fc8671315f9c00
        entity_id: light.fan_light_2
        domain: light
      - type: turn_off
        device_id: f58957d7536a588f98369305882c9e6a
        entity_id: light.fan_light_3
        domain: light
    default: []
  mode: single
- id: '1636943258539'
  alias: 'Hallway Button Pressed: Toggle Hallway Light'
  description: ''
  trigger:
  - device_id: 3693d5d22387569ba41807c486903bbd
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - type: toggle
    device_id: b71e4d4788bb167773237c28d61db7bb
    entity_id: switch.hallway_light
    domain: switch
  mode: single
- id: '1636996449089'
  alias: Study Lights
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: 907e341d89c5be672843b14a188fd193
    entity_id: binary_sensor.macbook_active
    domain: binary_sensor
    id: macbook_active
  - type: turned_off
    platform: device
    device_id: 907e341d89c5be672843b14a188fd193
    entity_id: binary_sensor.macbook_active
    domain: binary_sensor
    id: macbook_inactive
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: macbook_active
      sequence:
      - type: turn_on
        device_id: bf9e68dfb382267abb0c244d9929360e
        entity_id: light.lamp
        domain: light
      - type: turn_on
        device_id: cbfe7f94d75c71a41271077c0554c814
        entity_id: light.desk_lamp
        domain: light
    - conditions:
      - condition: trigger
        id: macbook_inactive
      sequence:
      - type: turn_off
        device_id: bf9e68dfb382267abb0c244d9929360e
        entity_id: light.lamp
        domain: light
      - type: turn_off
        device_id: cbfe7f94d75c71a41271077c0554c814
        entity_id: light.desk_lamp
        domain: light
    default: []
  mode: restart
- id: '1637124125495'
  alias: 'Arrive Home: Hallway Light On'
  description: ''
  trigger:
  - platform: zone
    entity_id: person.marisa_clardy
    zone: zone.home
    event: enter
  condition: []
  action:
  - wait_for_trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      to: open
  - service: tts.cloud_say
    data:
      entity_id: media_player.kitchen
      message: Welcome Home!
      cache: true
  - type: turn_on
    device_id: b71e4d4788bb167773237c28d61db7bb
    entity_id: switch.hallway_light
    domain: switch
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: b71e4d4788bb167773237c28d61db7bb
    entity_id: switch.hallway_light
    domain: switch
  mode: single
- id: '1637429968086'
  alias: Kitchen Motion Lights
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 962c98d6430a6688cbf465747c5a0e7a
    entity_id: binary_sensor.kitchen_motion
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: input_select.system_mode
    state: Home
  action:
  - type: turn_on
    device_id: c136c02ac81d79ade4781284c42869bc
    entity_id: switch.kitchen_light
    domain: switch
  - wait_for_trigger:
    - type: no_motion
      platform: device
      device_id: 962c98d6430a6688cbf465747c5a0e7a
      entity_id: binary_sensor.kitchen_motion
      domain: binary_sensor
    continue_on_timeout: true
    timeout: 00:25:00
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: c136c02ac81d79ade4781284c42869bc
    entity_id: switch.kitchen_light
    domain: switch
  mode: restart
- id: '1637817372671'
  alias: Lights off at midnight
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - scene: scene.bedroom_lights_off
  - type: turn_off
    device_id: c136c02ac81d79ade4781284c42869bc
    entity_id: switch.kitchen_light
    domain: switch
  - type: turn_off
    device_id: 69b1ccedd2cc904b45e26ace20117573
    entity_id: light.tv_backlights
    domain: light
  - type: turn_off
    device_id: 09d911bf1269455d7b6e302e06eea4ea
    entity_id: light.couch_lamp
    domain: light
  - type: turn_off
    device_id: cbfe7f94d75c71a41271077c0554c814
    entity_id: light.desk_lamp
    domain: light
  - type: turn_off
    device_id: b5bab84823b70c1214acc60cee91996f
    entity_id: light.rectangulamp
    domain: light
  - type: turn_off
    device_id: bf9e68dfb382267abb0c244d9929360e
    entity_id: light.lamp
    domain: light
  - type: turn_off
    device_id: c10e8b604af4f4c22e62f377c6ecca87
    entity_id: switch.cube_light_on_off
    domain: switch
  - type: turn_off
    device_id: b71e4d4788bb167773237c28d61db7bb
    entity_id: switch.hallway_light
    domain: switch
  - type: turn_off
    device_id: f84cd5c0ed24eaf6c3a25c4f7046b484
    entity_id: switch.christmas_tree_on_off
    domain: switch
  mode: single
- id: '1637979359844'
  alias: Automatic Blinds
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    id: sunrise
    offset: '-45'
  - platform: sun
    event: sunset
    id: sunset
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: sunrise
      sequence:
      - device_id: d9d9e42e45e105ad8b430a2618b8e8df
        domain: cover
        entity_id: cover.bedroom_side_blinds
        type: set_position
        position: 100
    - conditions:
      - condition: trigger
        id: sunset
      sequence:
      - device_id: d9d9e42e45e105ad8b430a2618b8e8df
        domain: cover
        entity_id: cover.bedroom_side_blinds
        type: set_position
        position: 0
    default: []
  mode: single
- id: '1638224503187'
  alias: Closet Light
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 24f0cbaa146a7cf8102c68fdc0341b09
    entity_id: binary_sensor.closet_door_open
    domain: binary_sensor
    id: door_open
  - type: not_opened
    platform: device
    device_id: 24f0cbaa146a7cf8102c68fdc0341b09
    entity_id: binary_sensor.closet_door_open
    domain: binary_sensor
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: door_open
      sequence:
      - type: turn_on
        device_id: 50288c95c83a403ec3e68cb488b6e97f
        entity_id: light.closet_light
        domain: light
    default:
    - type: turn_off
      device_id: 50288c95c83a403ec3e68cb488b6e97f
      entity_id: light.closet_light
      domain: light
  mode: queued
  max: 10
- id: '1638226343221'
  alias: Toggle Bedroom Blinds
  description: ''
  trigger:
  - device_id: 3693d5d22387569ba41807c486903bbd
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: remote_button_long_press
  - device_id: 36ba91f41f19c8a6fa4d4f915da8020c
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_down
  condition: []
  action:
  - choose:
    - conditions:
      - condition: device
        device_id: d9d9e42e45e105ad8b430a2618b8e8df
        domain: cover
        entity_id: cover.bedroom_side_blinds
        type: is_position
        below: 7
      sequence:
      - device_id: d9d9e42e45e105ad8b430a2618b8e8df
        domain: cover
        entity_id: cover.bedroom_side_blinds
        type: set_position
        position: 100
    - conditions:
      - condition: device
        device_id: d9d9e42e45e105ad8b430a2618b8e8df
        domain: cover
        entity_id: cover.bedroom_side_blinds
        type: is_position
        above: 93
      sequence:
      - device_id: d9d9e42e45e105ad8b430a2618b8e8df
        domain: cover
        entity_id: cover.bedroom_side_blinds
        type: set_position
        position: 0
    default: []
  mode: single
- id: '1638744616530'
  alias: Turn on Christmas Tree in the morning
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '0'
  condition: []
  action:
  - type: turn_on
    device_id: f84cd5c0ed24eaf6c3a25c4f7046b484
    entity_id: switch.christmas_tree_on_off
    domain: switch
  mode: single
- id: '1639000471493'
  alias: Wallmote Quad Buttons
  description: ''
  use_blueprint:
    path: marisa/wallmote-quad.yaml
    input:
      wallmote_quad_device: faec83aec8ea4c3535930b6276038337
      button_1_pressed:
      - type: toggle
        device_id: bf9e68dfb382267abb0c244d9929360e
        entity_id: light.lamp
        domain: light
      - type: toggle
        device_id: cbfe7f94d75c71a41271077c0554c814
        entity_id: light.desk_lamp
        domain: light
