# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
prometheus:
camera: !include camera.yaml
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5
python_script:

homeassistant:
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

media_player: !include media_players.yaml

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
