#########################
# General Configuration #
#########################
default_config:

recorder:
  db_url: !secret db_url

homeassistant:
  customize: !include includes/customize.yaml

frontend:
  themes: !include_dir_merge_named themes

lovelace: !include includes/lovelace.yaml

influxdb:
  host: 192.168.68.56
  port: 8086
  database: homeassistant
  username: homeassistant
  password: ha-influxdb
  max_retries: 3
  default_measurement: state

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.68.60
  ip_ban_enabled: true
  login_attempts_threshold: 5

tts:
- platform: google_translate

###############
# Automations #
###############
automation ui: !include automations.yaml
automation manual: !include_dir_merge_list includes/automations/
script ui: !include scripts.yaml
script manual: !include_dir_merge_list includes/scripts/
scene ui: !include scenes.yaml
scene manual: !include_dir_merge_list includes/scene/

###############################
# Manually Configured Sensors #
###############################
group: !include includes/groups.yaml
sensor: !include includes/sensors.yaml
switch: !include includes/switches.yaml
binary_sensor: !include includes/binary_sensors.yaml
camera: !include includes/camera.yaml
media_player: !include includes/media_players.yaml
template: !include includes/template_sensors.yaml
browser_mod:
  prefix: 'browser_mod_'
python_script:
momentary:
zha: !include includes/zha.yaml
proxmoxve: !include includes/proxmoxve.yaml
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret