- platform: min_max
  name: Average Temperature
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.hallway_temperature
    - sensor.kitchen_temperature
    - sensor.living_room_temperature
    - sensor.living_room_2_temperature
    - sensor.study_temperature
    - sensor.bedroom_temperature
